
version: '2'

services:
  eitem-service:
    build: ./electronics-item
    volumes:
      - ./electronics-item:/usr/src/app
    ports:
      - 5002:80
  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5005:80
    depends_on:
      - eitem-service
